# CI de Nível 03 - Disparo após a conclusão de um pipeline
# nome do nosso 'pipeline'

name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_run:
    workflow: ['Execução Manual']
      types:
        - completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das depedencias
      - name: Instalando dependencias
        run: yarn

      # instalação do playright
      - name: Instalando playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
